<a href="https://colab.research.google.com/github/kaneserignembacke260-beep/titanic-ml-pipeline/blob/main/03_pandas_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
#  permet d'importer pandas en utilisant pd

In [9]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
# ce bout de code permet de  lire le tableau csv

In [10]:
df.head()
#pemet de voir les 5 premieres lignes du tableau

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df.shape
# permet de savoir les lignes et les colonnes

(891, 12)

In [12]:
df.info()
#permet de voir les informations du tableau
# Non-Null Count = nombre de valeurs remplies (non vides) par colonne
# Dtype = type de donnée de la colonne (int64 = entier, float64 = décimal, object = texte)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Gérer les valeurs manquantes

Après avoir obtenu les informations générales sur le DataFrame, il est important de vérifier la présence de valeurs manquantes (NaN). Celles-ci peuvent affecter l'analyse et la modélisation, et doivent être traitées de manière appropriée (par exemple, imputation, suppression de lignes/colonnes).

In [13]:
df.isnull().sum()
# Cette ligne de code permet de compter le nombre de valeurs manquantes par colonne.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [15]:
df[["Age", "Survived"]]

      Age  Survived
0    22.0         0
1    38.0         1
2    26.0         1
3    35.0         1
4    35.0         0
..    ...       ...
886  27.0         0
887  19.0         1
888   NaN         0
889  26.0         1
890  32.0         0

[891 rows x 2 columns]

In [16]:
df["Survived"] == 1
# crée une nouvelle colonne true or false (true si le passager à survécu )

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Survived, Length: 891, dtype: bool

In [17]:
survivants = df[df["Survived"] == 1]
survivants.head()
#df["Survived"] == 1 → crée la colonne de True/False que tu as vue juste avant
#df[ ... ] → dit à pandas : "ne garde que les lignes où c'est True"
#On stocke le résultat dans une nouvelle variable survivants
#df.head() → pour afficher les 5 premières lignes de ce nouveau DataFrame filtré

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [18]:
df.loc[0:5, "Name"]
# sélectionne les lignes et colonnes mais la deniére borne est incluse
# les 5 premiéres lignes de la colonne  name

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
Name: Name, dtype: object

In [19]:
df.iloc[0:5, 0:3]
#  sélectionne les lignes et colonnes
# un  bout de dataframe

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

In [20]:
# une ligne de code qui sélectionne seulement  les pclase
df["Pclass"]

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [21]:
premiere_classe=df[df["Pclass"]==1]
premiere_classe.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [22]:
df.iloc[0:4,0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1

In [23]:
# describe() : donne un résumé statistique des colonnes numériques du dataset
# - count : nombre de valeurs non manquantes
# - mean  : moyenne (somme des valeurs / nombre de valeurs)
# - std   : écart-type = dispersion des valeurs autour de la moyenne
# - min / max : valeur la plus petite / la plus grande
# - 25% / 50% / 75% : quartiles → valeurs qui divisent le dataset trié
#   (50% = médiane, la valeur du milieu)
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [24]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [25]:
df["Name"].value_counts()

Name
Dooley, Mr. Patrick                                    1
Braund, Mr. Owen Harris                                1
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Heikkinen, Miss. Laina                                 1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
                                                      ..
Hewlett, Mrs. (Mary D Kingcome)                        1
Vestrom, Miss. Hulda Amanda Adolfina                   1
Andersson, Mr. Anders Johan                            1
Saundercock, Mr. William Henry                         1
Bonnell, Miss. Elizabeth                               1
Name: count, Length: 891, dtype: int64

In [26]:
df.groupby("Sex")["Survived"].mean()
# df.groupy("col") ici sexe permet de regrouper toutes  les lignes en  2  homme et femme
# on regarde que la colonne des survived
#  on calcule la moyenne à partir de male et femelle

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [27]:
df.groupby("Pclass")["Survived"].mean()
# calcul le pourcentage dess  classes (1,2,3)
#  on constate que la classe 1 a la plus grande pourcentage de survie

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [28]:
df.groupby("Embarked")["Survived"].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64